global_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint
   map_type: costmap
   update_frequency: 3.0
   publish_frequency: 0.0
   transform_tolerance: 0.5
   width: 100
   height: 100
   resolution: 0.05
   origin_x: -50.0
   origin_y: -50.0
