controller_frequency: 20.0
base_local_planner: dwa_local_planner/DWAPlannerROS
recovery_behaviors:
  - name: rotate_recovery
    type: rotate_recovery/RotateRecovery
  - name: aggressive_reset
    type: clear_costmap_recovery/ClearCostmapRecovery

# Configuration for recovery behaviors
aggressive_reset:
  # When doing an aggressive reset, remove all voxels from the
  # costmap.
  reset_distance: 0.01

# See also costmap_common_params.yaml for additional parameters set
# for the two costmaps.
local_costmap:
   global_frame: /odom
   robot_base_frame: /base_footprint
   map_type: voxel
   update_frequency: 5.0
   publish_frequency: 5.0
   static_map: false
   rolling_window: true
   width: 4.0
   height: 4.0
   resolution: 0.025
   transform_tolerance: 0.5
   unknown_cost_value: 100

global_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint
   map_type: costmap
   update_frequency: 3.0
   publish_frequency: 0.0
   transform_tolerance: 0.5
   width: 100
   height: 100
   resolution: 0.05
   origin_x: -50.0
   origin_y: -50.0

DWAPlannerROS:
  acc_lim_th: 8.0
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  max_trans_vel: 0.55
  min_trans_vel: 0.0
  max_vel_x: 0.55
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_rot_vel: 1.5
  min_rot_vel: 0.0
  # These are guessed tolerance values. Yaw tolerance should be about
  # 45 degree and xy tolerance within a foot.
  yaw_goal_tolerance: 0.4  # radians
  xy_goal_tolerance: 0.5  # meters
  stop_time_buffer: 0.8
  forward_point_distance: 0.4
  vy_samples: 0
  vtheta_samples: 40
  
TrajectoryPlannerROS:
  # Set the velocity values to something that matches our
  # platform. However, these values have been sort of guessed and it's
  # likely that they can be improved.
  max_vel_x: 0.55
  min_vel_x: 0.4
  max_rotational_vel: 0.6
  min_in_place_rotational_vel: 0.2
  acc_lim_th: 8.0
  acc_lim_x: 1.0
  acc_lim_y: 0.0

  holonomic_robot: false

  # These are guessed tolerance values. Yaw tolerance should be about
  # 45 degree and xy tolerance within a foot.
  yaw_goal_tolerance: 0.4  # radians
  xy_goal_tolerance: 0.5  # meters
  escape_vel: 0.0  # Backup velocity, must be negative!
  
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  sim_time: 1.5
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05

  vx_samples: 6
  vtheta_samples: 20
  dwa: false

NavfnROS:
  default_tolerance: 0.5
